const assert=require('node:assert/strict');
const {observationInput,validate,publishSections}=require('./run-gemini-typebeat.cjs');
const report={analysis:{audioAccess:'available',summary:'bass groove',observations:[{description:'syncopated bass'}],instrumentalAdaptation:{possibleChanges:['ADD VOCAL CHOPS']}}};
const input=observationInput(report);
assert(!JSON.stringify(input).includes('ADD VOCAL CHOPS'));
assert.equal(input.observations[0].confidence,'not supplied');
assert.equal(input.observations[0].id,'O1');
assert.equal(observationInput({...report,userIntent:'warm melancholy'}).userIntent,'warm melancholy');
assert.throws(()=>observationInput({analysis:{audioAccess:'unavailable'}}));
assert(validate({style:'x'.repeat(1001),section:'[Intro]\nplain directions'}).includes('style exceeds 1000'));
const section=['Intro','Instrumental Hook 1','Instrumental Verse 1','Instrumental Hook 2','Instrumental Bridge','Instrumental Hook 3','Outro'].map(h=>`[${h}]\n(Change.)`).join('\n\n');
const output={direction:{identity:'new beat',relationships:[],moodBasis:{core:'tense',evidenceIds:['O1'],localOnly:[],uncertainty:''}},style:'Instrumental club beat.',section};
assert.deepEqual(validate(output,input),[]);
output.direction.moodBasis.evidenceIds=['O99'];
assert(validate(output,input).includes('Unknown mood evidence ID'));
const draft={style:'Instrumental.',section:'Do not publish this stale field',sectionChanges:['Intro','Instrumental Hook 1','Instrumental Verse 1','Instrumental Hook 2','Instrumental Bridge','Instrumental Hook 3','Outro'].map(header=>({header,instruction:'Let the bass answer in the gap.',benefit:'PRIVATE_REASON'}))};
const published=publishSections(draft);
assert(!published.section.includes('PRIVATE_REASON'));
assert(!published.section.includes('stale'));
assert(published.section.includes('[Instrumental Hook 3]\n(Let the bass answer in the gap.)'));
assert.equal(draft.section,'Do not publish this stale field');
assert.throws(()=>publishSections({...draft,sectionChanges:draft.sectionChanges.slice(1)}));
assert.throws(()=>publishSections({...draft,sectionChanges:draft.sectionChanges.map(x=>({...x,instruction:''}))}));
console.log('Observation-only transfer and publication format checks passed (offline).');
