// Offline integration checks: repeated lyrics, output limits and stale responses.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const nodes={};
const ctx=vm.createContext({console,document:{getElementById:id=>nodes[id]??=( {value:'',style:{}} )},showToast:()=>{},updateFloatSummary:()=>{},getOpenAIKey:()=> 'fixture'});
const app=fs.readFileSync('app.js','utf8');
for(const f of ['hh-data.js','hh-ai.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
ctx.getOpenAIKey=()=> 'fixture';
ctx.checkMusicConditions=async()=>[];
ctx.buildMusicPlan=async({spec,context})=>{assert.deepEqual(Object.keys(context.narrAI),[]);return {identity:'fixture',roles:[],sections:spec.structure.map(x=>({...x,direction:'Maintain the intention.'}))};};
vm.runInContext(`const antiAI=true;const VTS={pop:{genre:'neo soul',bpm:100,key:7,mood:null,instruments:['피아노','베이스','드럼'],vocalStyle:null,concept:'',userLyrics:'',refSong:'',narrSt:{},structSegs:['verse','chorus']}};`,ctx);
vm.runInContext(app.slice(app.indexOf('const POP_VOCAL_GUIDE='),app.indexOf('// TOAST')),ctx);
const run=s=>vm.runInContext(s,ctx);
const unset=run('({...VTS.pop,bpm:null,key:null,lyricLang:"日本語"})');
assert.equal(ctx.popWriteSpec(unset).bpm,null);assert.equal(ctx.popWriteSpec(unset).key,null);
assert.equal(ctx.popWriteSpec(unset).lyricPlan.language,'日本語');
assert.doesNotMatch(ctx.popStylePrompt(unset,null,null,null),/BPM|A minor|null|undefined/);
assert.match(ctx.popLyricsPrompt(unset),/original 日本語 lyrics/);
assert.equal(ctx.popWriteSpec({...unset,bpm:118,key:18}).key,'A major');

for(const tag of run('POP_GENRES.map(g=>g.tag)')){
  ctx.tag=tag;
  const text=run(`popStylePrompt({...VTS.pop,...POP_AUTO[tag],narrSt:POP_AUTO[tag]?.narr||{}},POP_GENRES.find(g=>g.tag===tag),null,120)`);
  assert.ok(text.length<=1000,`${tag}: ${text.length}`);
}
assert.doesNotThrow(()=>ctx.checkPopBudget('x'.repeat(5000),'x'.repeat(1000)));
assert.throws(()=>ctx.checkPopBudget('x'.repeat(5001),'x'));
assert.throws(()=>ctx.checkPopBudget('x','x'.repeat(1001)));
const base='[Verse]\n(Soft piano.)\n[Chorus]\n(Wider piano.)';
ctx.base=base;
assert.throws(()=>ctx.mergePopLyricsAndSection(base,'[Bridge]\nUnmatched lyric'));
ctx.refineMusicPlan=async(_spec,plan)=>plan;
ctx.checkTypeBeatAlignment=async(_spec,result)=>({result,note:''});
(async()=>{
  run('popBaseSection=base;');nodes['pop-style-ta']={value:'Soulful pop.'};
  ctx.callOpenAI=async(_key,r)=>{assert.match(r.staticText,/Write lyrics in 한국어/);return '<lyrics>[Verse]\nOld verse\n[Chorus]\nOld hook</lyrics>';};
  await ctx.popGenerateLyrics();
  ctx.callOpenAI=async()=>'<lyrics>[Verse]\nNew verse\n[Chorus]\nNew hook</lyrics>';
  await ctx.popGenerateLyrics();
  assert.doesNotMatch(nodes['pop-sect-ta'].value,/Old/);
  assert.match(nodes['pop-sect-ta'].value,/\(Soft piano\.\)\nNew verse/);
  ctx.popEditLyrics('[Verse]\nEdited verse\n[Chorus]\nEdited hook');
  assert.match(nodes['pop-sect-ta'].value,/Edited verse/);
  assert.doesNotMatch(nodes['pop-sect-ta'].value,/New verse/);
  const previous=nodes['pop-sect-ta'].value;
  ctx.popEditLyrics('[Bridge]\nWrong section');
  assert.equal(nodes['pop-sect-ta'].value,previous);
  assert.match(nodes['pop-ai-status'].textContent,/미반영/);
  run("VTS.pop.userLyrics='';");
  ctx.callOpenAI=async()=>'<lyrics>[Verse]\n'+'x'.repeat(5001)+'</lyrics>';
  await ctx.popGenerateLyrics();assert.equal(nodes['pop-sect-ta'].value,previous);
  let resolve;
  ctx.callOpenAI=()=>new Promise(r=>resolve=r);
  const pending=ctx.popAiWriteStyle(run('VTS.pop'),run('popWriteToken'));
  await new Promise(setImmediate);
  run('++popWriteToken;');resolve('<section>'+base+'</section><style>stale</style>');
  await pending;assert.equal(nodes['pop-style-ta'].value,'Soulful pop.');
  run('popStylePending=true;');ctx.callOpenAI=()=>{throw new Error('Must not request lyrics during style writing');};
  await ctx.popGenerateLyrics();assert.equal(nodes['pop-sect-ta'].value,previous);
  run('popStylePending=false;');
  let request;
  ctx.callOpenAI=async(key,r)=>{request=r;return '<section>'+base+'</section><style>Soulful pop at 100 BPM with a steady pulse and short bass answers.</style>';};
  await ctx.popAiWriteStyle(run('VTS.pop'),run('popWriteToken'));
  assert.ok(request.staticText.includes(run('PROMPT_ROLE_GUIDE')));
  assert.match(request.dynamicText,/\[명세\]/);
  assert.doesNotMatch(request.dynamicText,/Soft piano\.|Soulful pop\./);
  assert.match(nodes['pop-style-ta'].value,/short bass answers/);
  // Incomplete structures are retried once and retained in diagnostics, never marked complete.
  let writes=0;ctx.callOpenAI=async()=>{writes++;return '<style>Warm soul.</style><section>[Verse]\n(Keys.)</section>';};
  const validSection=nodes['pop-sect-ta'].value;
  await ctx.popAiWriteStyle(run('VTS.pop'),run('popWriteToken'));
  assert.equal(writes,2);assert.match(nodes['pop-ai-status'].textContent,/실패/);
  assert.equal(nodes['pop-sect-ta'].value,validSection);
  assert.ok(run('popDiagnostic.attempts.some(x=>x.output?.section.includes("[Verse]"))'));
  // Overlong new lyrics get a bounded rewrite; manually supplied lyrics bypass rewriting.
  run("VTS.pop.userLyrics='';popBaseSection=base;");nodes['pop-style-ta'].value='Soulful pop.';
  let lyricCalls=0;ctx.callOpenAI=async()=>++lyricCalls===1?'<lyrics>[Verse]\n'+'x'.repeat(5100)+'\n[Chorus]\nHook</lyrics>':'<lyrics>[Verse]\nSmall room\n[Chorus]\nCome home</lyrics>';
  await ctx.popGenerateLyrics();assert.equal(lyricCalls,2);assert.match(nodes['pop-sect-ta'].value,/Come home/);
  assert.ok(run('popDiagnostic.attempts[0].raw.length>5000'));
  run(String.raw`popBaseSection='[Intro]\n(Piano only.)\n[Verse]\n(Voice enters.)';popMusicPlan={sections:[{header:'[Intro]',vocalMode:'instrumental'},{header:'[Verse]',vocalMode:'lyrics'}]};`);
  lyricCalls=0;ctx.callOpenAI=async()=>++lyricCalls===1?'<lyrics>[Intro]\nWrong entrance\n[Verse]\nHello</lyrics>':'<lyrics>[Intro]\n[Verse]\nHello</lyrics>';
  await ctx.popGenerateLyrics();
  assert.equal(lyricCalls,2);assert.doesNotMatch(nodes['pop-sect-ta'].value,/Wrong entrance/);
  assert.match(run('popDiagnostic.attempts[0].error'),/인스트루멘탈/);
  console.log('PASS: pop budgets, repeated lyrics, unmatched headers, stale responses and pending guard.');
})().catch(e=>{console.error(e);process.exitCode=1;});
