const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({console,setTimeout,clearTimeout});
vm.runInContext(fs.readFileSync('hh-data.js','utf8'),c);
vm.runInContext(fs.readFileSync('hh-ai.js','utf8'),c);
let request;
c.recoverAiFormat=async(stage,r)=>{request=r;return {style:'Instrumental at 105 BPM in A# minor.',section:'[Intro]\n(Dry drums.)',lyrics:''};};
c.buildReferenceV3=()=>{throw Error('Legacy design called');};
c.st={narrAI:{hook:'More rhythmic movement'},extraTags:[],removedPhrases:[]};
(async()=>{
 const spec={designMode:'reference-type-beat',referenceSong:'LE SSERAFIM - ANTIFRAGILE',bpm:105,key:'A# minor',structure:[{header:'[Intro]'}],brief:{instrumentalProfile:{instruments:'STALE WHISTLE'}},lead:'STALE LEAD',userChoices:{mood:'confident'}};
 const plan=await c.buildMusicPlan({spec});assert.equal(plan.referenceVersion,'direct');
 assert.equal(await c.refineMusicPlan(spec,plan),plan);
 assert.equal((await c.checkMusicConditions(spec,plan)).length,0);
 const out=await c.writeOnce({spec,mode:'create'});
 const data=JSON.parse(request.dynamicText);assert.equal(data.bpm,105);assert.equal(data.key,'A# minor');assert.equal(data.userChoices.mood,'confident');assert(!request.dynamicText.includes('STALE'));assert(!request.dynamicText.includes('musicPlan'));
 assert.equal((await c.checkTypeBeatAlignment(spec,out)).result,out);
 await c.writeOnce({spec,mode:'edit',prev:out});assert(JSON.parse(request.dynamicText).feedback.directions.hook);
 await assert.rejects(()=>c.writeReferenceDirect({spec:{...spec,bpm:null}}),/BPM/);
 await c.writeOnce({spec:{...spec,vocal:'Sung lead vocal'},mode:'create'});
 assert.equal(JSON.parse(request.dynamicText).vocal,'Sung lead vocal');
 const elements={'hh-ref-song':{value:''},'hh-brief':{value:''}};
 c.document={getElementById:id=>elements[id]||null};c.markPending=()=>{};
 c.autoAnalyzeReference=()=>{throw Error('Selection triggered analysis');};
 c.hhGenerate=()=>{throw Error('Selection triggered generation');};
 c.setRefSongFromPicker('LE SSERAFIM - ANTIFRAGILE',null);
 assert.equal(elements['hh-ref-song'].value,'LE SSERAFIM - ANTIFRAGILE');
 const generate=fs.readFileSync('app.js','utf8').split('function hhGenerate(source,opts){')[1].split('// MD 저장')[0];
 assert(!generate.includes('autoAnalyzeReference('));
 console.log('Direct route, no legacy design, no inferred instrumentation, edits and missing parameters OK');
})().catch(e=>{console.error(e);process.exitCode=1});
