const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({});vm.runInContext(fs.readFileSync('reference-v2.js','utf8'),c);
const fields={mood:{basis:'model-knowledge',scope:'track',reason:'specific memory'},groove:{basis:'web-source',scope:'track',reason:'summary describes rhythm',sources:[{url:'https://example.org'}],supportMatched:true},bass:{basis:'inference',scope:'track',reason:'groove suggests a supporting pulse',anchors:['groove']},activity:{basis:'inference',scope:'track',reason:'bass and groove',anchors:['bass']},balance:{basis:'inference',scope:'track',reason:'',anchors:[]},instruments:{basis:'model-knowledge',scope:'artist-genre',reason:'catalog'},energy:{basis:'unknown',scope:'unknown'},arrangement:{basis:'web-source',scope:'track',reason:'url alone',sources:[{url:'https://example.org'}]},timbreSpace:{basis:'user-description',scope:'track',reason:'user observation',supportMatched:true}};
const p={instrumentalProfile:Object.fromEntries(Object.keys(fields).map(k=>[k,'description '+k])),analysisEvidence:fields};const out=c.filterReferenceV2(p);
assert.equal(out.analysisEvidence.bass.status,'interpretation');assert.equal(out.analysisEvidence.activity.status,'interpretation');assert.equal(out.analysisEvidence.mood.status,'model-recollection');
assert.equal(out.analysisEvidence.arrangement.status,'evidence-missing');assert.equal(out.analysisEvidence.energy.status,'unknown');assert.equal(out.analysisEvidence.instruments.status,'general-context');assert.equal(out.instrumentalProfile.balance,undefined);assert.equal(out.unresolvedProfile.balance.description,'description balance');assert.equal(p.instrumentalProfile.balance,'description balance');assert.equal(out.instrumentalProfile.timbreSpace,'description timbreSpace');
assert.equal(JSON.stringify(c.filterReferenceV2(out).instrumentalProfile),JSON.stringify(out.instrumentalProfile));
const cyc={instrumentalProfile:{a:'a',b:'b'},analysisEvidence:{a:{basis:'inference',scope:'track',reason:'r',anchors:['b']},b:{basis:'inference',scope:'track',reason:'r',anchors:['a']}}};assert.equal(Object.keys(c.filterReferenceV2(cyc).instrumentalProfile).length,0);
console.log('PASS: provenance statuses, useful inference chains, unsupported cycles, no mutation, unresolved text preserved');
