const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({console,AbortSignal});for(const f of ['hh-data.js','reference-v2.js','reference-v3.js','hh-ai.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);
const row=JSON.parse(fs.readFileSync('reports/role-fit-live-recheck.json')).find(r=>r.name==='someone-like-you');
const base=row.plan,before=JSON.stringify(base),change={roleIndex:0,sectionIndex:1,direction:'In bars 3–4 briefly shape the upper chord notes into a melody at the same pulse, then resume accompaniment.',benefit:'같은 반주 안에서 잠깐 선율의 응답을 만든다.'};
const changed=c.applyReferenceV3Change(base,change);
assert.equal(JSON.stringify(base),before);assert.equal(JSON.stringify(changed.roles),JSON.stringify(base.roles));assert.equal(JSON.stringify(changed.identityCore),JSON.stringify(base.identityCore));assert.equal(JSON.stringify(changed.vocalHandling),JSON.stringify(base.vocalHandling));
for(let i=0;i<base.sections.length;i++)if(i!==1)assert.equal(JSON.stringify(changed.sections[i]),JSON.stringify(base.sections[i]));
assert.match(c.referenceV3Publication(changed).sections[1].direction,/Local exception/);
for(const bad of [{...change,roles:[]},{...change,roleIndex:99},{...change,sectionIndex:-1},{...change,sectionIndex:'1'},{...change,direction:''}])assert.throws(()=>c.applyReferenceV3Change(base,bad));
const pair=[change,{...change,roleIndex:1,direction:'Keep the upper line out in these bars so the accompaniment can answer; resume its existing role afterwards.'},{...change,sectionIndex:2,direction:'Return to the baseline accompaniment throughout this verse.'}];
const combined=c.applyReferenceV3Changes(base,pair);
assert.equal(JSON.stringify(base),before);assert.equal(JSON.stringify(combined.roles),JSON.stringify(base.roles));
assert.match(combined.sections[1].direction,/Keep the upper line out/);assert.match(combined.sections[2].direction,/throughout this verse/);
assert.equal(JSON.stringify(combined.sections[0]),JSON.stringify(base.sections[0]));
assert.throws(()=>c.applyReferenceV3Changes(base,[change,change]));
assert.throws(()=>c.applyReferenceV3Changes(base,[change,{...change,sectionIndex:999}]));
assert.equal(JSON.stringify(base),before);
(async()=>{
 let n=0;c.referenceV2Json=async()=>++n===1?{changes:[change]}:{scopeValid:false,decision:'apply',reason:'Hidden new drums are outside scope'};
 assert.equal(await c.selectReferenceV3Change(base,row.spec,row.analysis,[]),base);
 n=0;c.referenceV2Json=async()=>++n===1?{changes:[change]}:{scopeValid:true,decision:'keep',reason:'Current hook already serves the intent'};
 assert.equal(await c.selectReferenceV3Change(base,row.spec,row.analysis,[]),base);
 n=0;c.referenceV2Json=async()=>++n===1?{changes:[change]}:{scopeValid:true,decision:'apply',reason:'Local contrast preserves the pulse'};
 const applied=await c.selectReferenceV3Change(base,row.spec,row.analysis,[]);assert.equal(JSON.stringify(applied),JSON.stringify(changed));
 c.referenceV2Json=async()=>({changes:[]});assert.equal(await c.selectReferenceV3Change(base,row.spec,row.analysis,[]),base);
 c.referenceV2Json=async()=>({changes:[change],shared:{}});await assert.rejects(()=>c.selectReferenceV3Change(base,row.spec,row.analysis,[]));
 n=0;c.referenceV2Json=async(stage,prompt,input)=>{if(++n===1)return {changes:pair};assert.equal(input.changes.length,3);assert.match(input.combinedDesign.sections[1].direction,/Keep the upper line out/);return {scopeValid:true,decision:'apply',reason:'Coordinated exchange preserves the baseline'};};
 assert.equal(JSON.stringify(await c.selectReferenceV3Change(base,row.spec,row.analysis,[])),JSON.stringify(combined));
 assert.equal(JSON.stringify(base),before);console.log('PASS: immutable baseline, coordinated existing roles/sections, reject scope escape, keep/apply/no-op, publication inherits local change');
})().catch(e=>{console.error(e);process.exitCode=1});
